# Generated by Django 4.2.7 on 2023-11-30 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='book_cover_images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobApp.author')),
            ],
        ),
    ]
